name: Run tests on PR to master

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: cd node && npm ci

      - name: Run Lint
        run: cd node && npm run lint

      - name: Run tests
        run: cd node && npm test